const data = {
    object: {
        id: "ch_3PFmvzCWW92SCjp31VLjkU2R",
        object: "charge",
        amount: 5000,
        amount_captured: 5000,
        amount_refunded: 0,
        application: null,
        application_fee: null,
        application_fee_amount: null,
        balance_transaction: "txn_3PFmvzCWW92SCjp31EdS32Vk",
        billing_details: {
            address: {
                city: null,
                country: "US",
                line1: null,
                line2: null,
                postal_code: "80205",
                state: null,
            },
            email: "jcollingj@gmail.com",
            name: "Jacob Colling",
            phone: null,
        },
        calculated_statement_descriptor: "JCDV, LLC",
        captured: true,
        created: 1715560808,
        currency: "usd",
        customer: null,
        description: null,
        destination: null,
        dispute: null,
        disputed: false,
        failure_balance_transaction: null,
        failure_code: null,
        failure_message: null,
        fraud_details: {},
        invoice: null,
        livemode: false,
        metadata: {},
        on_behalf_of: null,
        order: null,
        outcome: {
            network_status: "approved_by_network",
            reason: null,
            risk_level: "normal",
            risk_score: 37,
            seller_message: "Payment complete.",
            type: "authorized",
        },
        paid: true,
        payment_intent: "pi_3PFmvzCWW92SCjp3192hXxWr",
        payment_method: "pm_1PFmvzCWW92SCjp37Qs9EfJC",
        payment_method_details: {
            card: {
                amount_authorized: 5000,
                brand: "visa",
                checks: {
                    address_line1_check: null,
                    address_postal_code_check: "pass",
                    cvc_check: "pass",
                },
                country: "US",
                exp_month: 2,
                exp_year: 2025,
                extended_authorization: {
                    status: "disabled",
                },
                fingerprint: "AnpZ9XmbeduK6HH1",
                funding: "credit",
                incremental_authorization: {
                    status: "unavailable",
                },
                installments: null,
                last4: "4242",
                mandate: null,
                multicapture: {
                    status: "unavailable",
                },
                network: "visa",
                network_token: {
                    used: false,
                },
                overcapture: {
                    maximum_amount_capturable: 5000,
                    status: "unavailable",
                },
                three_d_secure: null,
                wallet: null,
            },
            type: "card",
        },
        radar_options: {},
        receipt_email: null,
        receipt_number: null,
        receipt_url:
            "https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xTzhFajNDV1c5MlNDanAzKOrChbIGMgah7uHlyQM6LBZhmbz-SiDru5rvSmsz_W2ZNnluLhet90uQoM0O7UtwRRFqH83bSzHa-WEP",
        refunded: false,
        review: null,
        shipping: null,
        source: null,
        source_transfer: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: "succeeded",
        transfer_data: null,
        transfer_group: null,
    },
    previous_attributes: {
        balance_transaction: null,
        receipt_url:
            "https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xTzhFajNDV1c5MlNDanAzKOvChbIGMgaStMSjHZI6LBau606Kug33Cye5Ulq_l27CARuYmEj-63piE222ICd66Zp_N6FgJV7IAEe1",
    },
};
const url =
    "https://script.google.com/macros/s/AKfycbzIOC4eyZ6ttfhONhBvrZZxYMNAqCT6K4RM-qkyGaCSsQ9yF1RJIxCGysbfMVrazeVfdg/exec";
const response = await fetch(url, {
    method: "POST",
    headers: {
        "Content-Type": "application/json",
    },
    body: JSON.stringify(data),
});
console.log(response);
console.log(await response.text());
